displayTitle macro title

mov ah,6
mov al,0
mov bh,01010000b
mov ch,3
mov cl,5
mov dh,3 
mov dl,74
int 10h

mov ah,6
mov al,0
mov bh,11000000b
mov ch,5
mov cl,5
mov dh,11 
mov dl,5
int 10h

mov ah,6
mov al,0
mov bh,11000000b
mov ch,5
mov cl,6
mov dh,5   
mov dl,7
int 10h

mov ah,6
mov al,0
mov bh,11000000b
mov ch,6
mov cl,8
mov dh,6   
mov dl,9
int 10h

mov ah,6
mov al,0
mov bh,11000000b
mov ch,7
mov cl,10
mov dh,7   
mov dl,11
int 10h

mov ah,6
mov al,0
mov bh,11000000b
mov ch,6
mov cl,12
mov dh,6   
mov dl,13
int 10h

mov ah,6
mov al,0
mov bh,11000000b
mov ch,5
mov cl,14
mov dh,5   
mov dl,15
int 10h

mov ah,6
mov al,0
mov bh,11000000b
mov ch,5
mov cl,16
mov dh,11   
mov dl,16
int 10h

mov ah,6
mov al,0
mov bh,00100000b
mov ch,9
mov cl,19
mov dh,11  
mov dl,20
int 10h

mov ah,6
mov al,0
mov bh,00100000b
mov ch,8
mov cl,20
mov dh,8   
mov dl,21
int 10h

mov ah,6
mov al,0
mov bh,00100000b
mov ch,7
mov cl,21
mov dh,7   
mov dl,22
int 10h

mov ah,6
mov al,0
mov bh,00100000b
mov ch,6
mov cl,22
mov dh,6   
mov dl,23
int 10h

mov ah,6
mov al,0
mov bh,00100000b
mov ch,5
mov cl,23
mov dh,5   
mov dl,24
int 10h

mov ah,6
mov al,0
mov bh,00100000b
mov ch,6
mov cl,24
mov dh,6   
mov dl,25
int 10h

mov ah,6
mov al,0
mov bh,00100000b
mov ch,7
mov cl,25
mov dh,7   
mov dl,26
int 10h

mov ah,6
mov al,0
mov bh,00100000b
mov ch,8
mov cl,26
mov dh,8   
mov dl,27
int 10h

mov ah,6
mov al,0
mov bh,00100000b
mov ch,9
mov cl,27
mov dh,11 
mov dl,28
int 10h

mov ah,6
mov al,0
mov bh,00100000b
mov ch,8
mov cl,21
mov dh,8   
mov dl,25
int 10h

mov ah,6
mov al,0
mov bh,11100000b
mov ch,5
mov cl,31
mov dh,11   
mov dl,31
int 10h

mov ah,6
mov al,0
mov bh,11100000b
mov ch,5
mov cl,31
mov dh,5   
mov dl,37
int 10h

mov ah,6
mov al,0
mov bh,11100000b
mov ch,6
mov cl,37
mov dh,7   
mov dl,37
int 10h

mov ah,6
mov al,0
mov bh,11100000b
mov ch,7
mov cl,31
mov dh,7  
mov dl,37
int 10h

mov ah,6
mov al,0
mov bh,11100000b
mov ch,8
mov cl,32
mov dh,8  
mov dl,33
int 10h

mov ah,6
mov al,0
mov bh,11100000b
mov ch,9
mov cl,34
mov dh,9  
mov dl,35
int 10h

mov ah,6
mov al,0
mov bh,11100000b
mov ch,10
mov cl,36
mov dh,10 
mov dl,37
int 10h

mov ah,6
mov al,0
mov bh,11100000b
mov ch,11
mov cl,37
mov dh,11 
mov dl,37
int 10h

mov ah,6
mov al,0
mov bh,10010000b
mov ch,5
mov cl,40
mov dh,5 
mov dl,48
int 10h

mov ah,6
mov al,0
mov bh,10010000b
mov ch,5
mov cl,44
mov dh,11 
mov dl,44
int 10h

mov ah,6
mov al,0
mov bh,10010000b
mov ch,11
mov cl,40
mov dh,11 
mov dl,48
int 10h

mov ah,6
mov al,0
mov bh,10110000b
mov ch,5
mov cl,53
mov dh,5 
mov dl,60
int 10h

mov ah,6
mov al,0
mov bh,10110000b
mov ch,6
mov cl,52
mov dh,6 
mov dl,53
int 10h

mov ah,6
mov al,0
mov bh,10110000b
mov ch,7
mov cl,51
mov dh,7 
mov dl,52
int 10h

mov ah,6
mov al,0
mov bh,10110000b
mov ch,8
mov cl,50
mov dh,8 
mov dl,51   
int 10h

mov ah,6
mov al,0
mov bh,10110000b
mov ch,9
mov cl,51
mov dh,9 
mov dl,52   
int 10h

mov ah,6
mov al,0
mov bh,10110000b
mov ch,10
mov cl,52
mov dh,10 
mov dl,53   
int 10h

mov ah,6
mov al,0
mov bh,10110000b
mov ch,11
mov cl,53
mov dh,11
mov dl,60   
int 10h

mov ah,6
mov al,0
mov bh,10110000b
mov ch,10
mov cl,60
mov dh,10 
mov dl,61   
int 10h

mov ah,6
mov al,0
mov bh,10110000b
mov ch,9
mov cl,61
mov dh,9 
mov dl,62   
int 10h

mov ah,6
mov al,0
mov bh,10110000b
mov ch,8
mov cl,62
mov dh,8 
mov dl,63   
int 10h

mov ah,6
mov al,0
mov bh,10110000b
mov ch,7
mov cl,61
mov dh,7 
mov dl,62   
int 10h

mov ah,6
mov al,0
mov bh,10110000b   
mov ch,6
mov cl,60
mov dh,6 
mov dl,61   
int 10h

mov ah,6
mov al,0
mov bh,11000000b
mov ch,5
mov cl,67
mov dh,9 
mov dl,68 
int 10h

mov ah,6
mov al,0
mov bh,11000000b
mov ch,11
mov cl,67
mov dh,11 
mov dl,68 
int 10h

mov ah,6
mov al,0
mov bh,11000000b
mov ch,5
mov cl,72
mov dh,9 
mov dl,73 
int 10h

mov ah,6
mov al,0
mov bh,11000000b
mov ch,11
mov cl,72
mov dh,11 
mov dl,73 
int 10h

mov ah,6
mov al,0
mov bh,01010000b
mov ch,13
mov cl,5
mov dh,13
mov dl,74
int 10h

endm